### ISSUE TITLE
compression of RGBA sometimes worse than 7-Zip (delta:4 LZMA2)

### ISSUE THREAD

**Issue by StephanBusch** [FLIF-hub/FLIF#158] opened 2015-11-13 09:09 UTC
There's an image that is compressed better with 7-Zip (delta:4 LZMA2)

https://drive.google.com/file/d/0ByLIAFlgldSoUUFQajRrTUpOeU0/view?usp=sharing
fractal.ppm 2.832.469 (7-Zip, 0=delta:4 1=LZMA2)
fractal.ppm 3.660.241 (FLIF 0.1.4)
fractal.ppm 3.661.091 (FLIF 0.1.1)

**Comment by jonsneyers** [comment] 2015-11-13 09:55
I can't reproduce this. I get a .flif file of size 2,202,068.

**Comment by StephanBusch** [comment] 2015-11-13 10:04
I forgot to mention that I tried the .PNG version of that image

**Comment by jonsneyers** [comment] 2015-11-13 10:33
Ah. Well, converting a PNG to PPM removes the alpha channel, so that's probably what explains the difference.

**Comment by jonsneyers** [comment] 2015-11-13 10:38
Try converting to PAM if you want to keep the alpha channel.

**Comment by StephanBusch** [comment] 2015-11-13 10:54
![fractal](https://cloud.githubusercontent.com/assets/15246743/11144466/24d4ddc4-89fd-11e5-8d93-482e496f9b4b.png)

PNGcheck tells me that fractal.png contains an alpha channel

**Comment by jonsneyers** [comment] 2015-11-13 12:15
Yes, and the alpha channel has a lot of entropy too.

With alpha:
8,294,471 fractal.pam
4,396,825 fractal.pam.7z  (`7z -m{0=delta:4,1=LZMA2}`)
4,250,028 fractal.pam.png
3,660,169 fractal.pam.flif

Flattened:
6,220,817 fractal.ppm
3,096,357 fractal.ppm.png
2,831,321 fractal.ppm.7z  (`7z -m{0=delta:3,1=LZMA2}`)
2,202,068 fractal.ppm.flif

**Comment by jonsneyers** [comment] 2015-11-13 20:19
Closing, considered solved.

**Closed by jonsneyers** 2015-11-13 20:19 UTC
