### ISSUE TITLE
CLA is not signed by all contributors

### ISSUE THREAD

**Issue by Lord-Nightmare** [FLIF-hub/FLIF#168] opened 2015-11-20 05:22 UTC
The CLA at https://github.com/FLIF-hub/FLIF-CLAs has been signed by 3 people so far (as of 20151119).
There are 17 contributors so far (as of 20151119) to https://github.com/FLIF-hub/FLIF
One of the contributors is jonsneyers, so that means there are 13 other contributors who have contributed code to FLIF, yet have not signed the CLA.
This needs to be rectified as soon as possible, otherwise later re-licensing of the code from GPLv3 to any other license becomes extremely difficult or impossible.

**Comment by jonsneyers** [comment] 2015-11-20 13:29
Well, if the contribution is small (just one or two lines of code), I don't think the contributor is really going to be able to stop me from changing the license ;)
@gitter-badger also doesn't really count as a contributor :) 

But yes, I agree, anyone who has made a contribution should sign that CLA.

**Comment by lucaswerkmeister** [comment] 2015-11-21 13:37
Perhaps you should wait until contributors have signed the CLA before merging their contributions? If, for example, @psykauze decides to not sign the CLA for some reason, you’re screwed unless you take #170 back out.

**Comment by psykauze** [comment] 2015-11-21 13:39
I've signed the CLA. Here the file

[psykauze-cla.txt](https://github.com/FLIF-hub/FLIF/files/40829/psykauze-cla.txt)

**Comment by jonsneyers** [comment] 2015-11-29 08:54
If we want to release the decoder under LGPL at the M1 release, then we're going to need those CLAs.

Who are we missing?

@TheJaredWilcurt only made changes to the README, so I guess that doesn't really have impact on the license.

@r-lyeh did some work on getting it compiled in Windows, and he added some public domain code to avoid dependencies on libpng and getopt. I suppose it would be best if we got a CLA from @r-lyeh to be sure.

@256bai also worked on Windows building. No code, only build instructions / build scripts. Not sure if a CLA is needed, but of course it doesn't hurt.

@ssbssa did some minor code tweaks; wouldn't hurt to get a CLA just to be sure.

@heavyk updated the Makefile, not sure if that has an impact on the license.

@waldyrious slightly changed the README.md, no impact on the license I guess.

@noshbar did a minor fix that was changed anyway a few commits later -- not really needed to get a CLA I think, but of course it doesn't hurt to get one.

@msm595 did a minor fix (one line of code), not really needed to get a CLA I think (would anyone really make a copyright claim based on that?), but of course it doesn't hurt to get one.

@gendx improved the code a bit, would be nice to get a CLA.

@skal65535 improved one line of code, wouldn't hurt to get a CLA.

Could the people mentioned here add their CLA to https://github.com/FLIF-hub/FLIF-CLAs please, so we can license the FLIF decoder under a more permissive license? Thanks!

**Comment by r-lyeh** [comment] 2015-11-29 10:51
done

**Comment by jonsneyers** [comment] 2015-11-30 13:15
OK, I think we got the main contributors covered. Only @gendx is missing -- I don't think the others made contributions that could impact the license.

From now on I will only accept push requests from contributors who signed the CLA.

**Comment by sipa** [comment] 2015-11-30 13:35
Do you want me to sign?

**Comment by jonsneyers** [comment] 2015-11-30 15:20
@sipa Well I consider you to be a co-author, so I wouldn't modify the license without your approval anyway. But I suppose you're fine with re-licensing to a more permissive license so you can just as well sign the CLA -- either way is fine.

I am currently considering to release a decoder-only library under the LGPL -- that should be enough to make it possible for any project (also proprietary ones) to read FLIF files.

The encoder I would like to keep GPL-only (at least for now). That should still allow it to be included in e.g. The GIMP or ImageMagick.

**Comment by r-lyeh** [comment] 2015-11-30 18:53
two suggestions

1. create a CLAs/ folder and remove the repo instead. From now, you can check quickly that with every new PR ready to merge has the corresponding CLA file. this becomes less tedious overall.

2. If the purpose of the decoder is to make the format available to a wider audience then the LGPL choice is controversial (I wouldnt use it for Example). Have you considered zlib/libpng license instead? Also for the encoder if it's about avoiding patents then maybe Apache2 license instead.

**Comment by gendx** [comment] 2015-11-30 20:54
Here is my CLA :
[FLIF-CLA-gendx.txt](https://github.com/FLIF-hub/FLIF/files/47788/FLIF-CLA-gendx.txt)

**Comment by jonsneyers** [comment] 2015-11-30 21:03
Thanks!

**Comment by jonsneyers** [comment] 2015-11-30 21:06
@r-lyeh Why would you not use a LGPL licensed library?

**Comment by Lord-Nightmare** [comment] 2015-11-30 21:21
@jonsneyers Not @r-lyeh here, but from what I understand, Apple's app store is incompatible with LGPL without some sort of additional exception clause added on to it.

**Comment by jonsneyers** [comment] 2015-11-30 22:03
Well, in my humble but perhaps somewhat stubborn opinion: if Apple wants to make it hard for their software "ecosystem" to use LGPL'ed libraries by not providing a distribution channel for anything but statically linked binary blobs, then I think that's their problem and their loss. If that means that developers of proprietary iOS apps have to spend more effort than other devs - FOSS devs or proprietary software devs on a sane platform that allows dynamic linking - just to be able to use my/our implementation of FLIF, then I consider that to be a feature, not a bug. I don't think it's my job to facilitate or encourage walled gardens.

I realize that others may have different feelings ;) but this is my opinion. However, I would perhaps consider to grant individual license exceptions e.g. to indie game devs, or even to big companies like Adobe or big mobile game studios, should they be interested in an even more permissive license than LGPL. Maybe we could sell license exceptions according to a model like this: http://www.fmod.org/sales/

**Comment by Lord-Nightmare** [comment] 2015-11-30 23:55
In my opinion, the Apache 2.0 license for the read-only library makes the most sense, and would result in the most adoption (other than flat MIT/BSD). It covers potential patent issues, and AFAIK is compatible with all of the various app-stores (to the best of my knowledge).

I think if the license is more restrictive than that for the reader it will just force people to write their own, more liberally licensed decoders, which not many people will really want to spend the effort to do, hence marginalizing the entire FLIF format.

**Comment by Two-Scoops** [comment] 2015-11-30 23:58
I know you feel strongly about FOSS, but as an image format I don't think you should be doing anything to hurt adoption. Webpages need to have support for all major browsers and I don't think they'll go out of their way to support FLIF files if a (quite significant) number of people aren't able to view them on their iPhones. FLIF would be  It doesn't really make sense to exclude FLIF from such a huge user-base, especially given the state of mobile phone plans.

If you really want to stay FOSS then licensing the encoder and decoder separately is the way to go. Force producers to go FOSS or implement it themselves, but allow consumers to consume unrestricted, otherwise FLIF is going to fail at its goals and remain a niche format.

**Comment by Lord-Nightmare** [comment] 2015-12-01 00:15
One important consideration regarding Apache 2.0, though: It is incompatible with GPLV2 and LGPLV2.1, so Dual-licensing the code as "Apache 2.0 or LGPLV2.1" and requiring all developers to allow distribution as both (which I believe the existing CLA already allows?) would be best for both the open source and app-store developer communities.

**Comment by vyp** [comment] 2015-12-01 00:39
> I don't think you should be doing anything to hurt adoption.

I don't think he is doing anything, it's more like Apple *is* doing something. I think that's an important distinction, but in a practical sense maybe that's just semantics. I find it sad (for FOSS) that one practically has to go with Apple or otherwise fade into irrelevance.

But maybe not! I think this should be viewed instead as an opportunity for FOSS to force Apple to change their ways. It's 'only' the iOS browsers that are missing out here, so in my opinion I still see the possibility that other major browsers will implement this, which will leave iOS users missing out, putting pressure on Apple.

I guess the key question here is whether other major browsers will consider implementing FLIF support if they already know it will not work on iOS browsers. I think they will, browser vendors always 'race' to implement flashy new features. (Of course, it first has to be part of a proposed web standard for them to do so.) And I believe they will want to because of the practical benefits that the format provides, which I think will outweigh their concerns about not supporting iOS users.

Otherwise, I'm all behind selling separate licensing exceptions as a nice 'compromise', but I would consider going laxer than LGPL 'giving up'. But that's just my two cents.

**Comment by Lord-Nightmare** [comment] 2015-12-01 02:36
I personally don't think modern developers would even consider a new media format unless it is compatible with all desktop and mobile devices.

There's basically 3 app stores:
Apple: GPL is outright forbidden, see http://www.zdnet.com/article/no-gpl-apps-for-apples-app-store/ (not sure how Colloquy is getting around this, unless their iOS app is completely BSD licensed...). LGPL is effectively forbidden due to static linking unless you manually add a static linking exception to the LGPL license, as noted at http://roadfiresoftware.com/2013/08/the-problem-with-using-lgpl-v2-1-code-in-an-ios-app/ .
Also, remember this is for all apps sold in the app store, this includes Desktop apps, which are becoming a large portion of apps available for OS X desktop as well, especially after OS X 10.10.

Windows Phone/Win 10 Store: Items now seem (didn't used to be the case?) to be allowed to use open source licenses via: "d. FOSS Software. If your App includes FOSS, (i) you are responsible for compliance with all applicable FOSS license terms, including any source code availability requirements, and (ii) it must not cause any non-FOSS Microsoft software to become subject to the terms of any FOSS license. " see https://msdn.microsoft.com/en-us/library/windows/apps/hh694058.aspx
It is unclear whether this outright forbids GPL/LGPL license in Windows Store apps, but it might for the same reason (static linking) that the Apple app store does. If so, a static linking exception would get around this.

Google Store: Unlike the other two, there seems to be a 'workaround' which allows LGPL apps in the store, see https://stackoverflow.com/a/18813205

**Comment by vyp** [comment] 2015-12-01 02:55
But windows phone doesn't really have much market share to cause a concern in my opinion. And android is not a walled garden like iOS is, i.e. you don't need the Google Play Store to install applications, therefore it doesn't matter even if the Play Store forbids (L)GPL apps.

**Comment by jonsneyers** [comment] 2015-12-01 16:59
Some remarks:
- iOS browsers can still run the JavaScript decoder fallback, which is going to be needed anyway.
- Even if we make our flif implementation __public domain__, there is still no guarantee whatsoever that Apple will actually include it in their browsers and other software.
- I don't see any reason why Google Chrome couldn't natively support FLIF using an LGPL'ed flif decode library: the source code to Chrome is available so even if they distribute statically linked binaries, it still satisfies the conditions of the LGPL, Unless I'm missing something. And Chrome is available on nearly all platforms, including iOS.
- The requirement of LGPL that ensures that users can re-link to modified/updated versions of the library is actually very important in this case: FLIF is a work in progress, and even though the goal is to make the format stable as soon as possible (as in future-safe), it is very likely that it will evolve and get more features in the future. I don't want people to be stuck with a blob that is statically linked with an outdated version of flif, with no possibility to upgrade it.
- A copyleft license for the reference implementation helps to ensure that the format remains free and open -- with a more permissive license (e.g. MIT or public domain), it is easier for some proprietary variant/extension of the original format to emerge and become the de facto standard. While such a thing has not happened with e.g. PNG, it is not impossible, especially in these "early days".

**Comment by jonsneyers** [comment] 2015-12-01 18:07
Closing this issue because the title has been resolved; the license discussion remains relevant though, and can continue in #192.

**Closed by jonsneyers** 2015-12-01 18:07 UTC
