### ISSUE TITLE
16bit depth decoding fail

### ISSUE THREAD

**Issue by psykauze** [FLIF-hub/FLIF#172] opened 2015-11-22 13:01 UTC
I've tried to decode RGGB fliffed file directly as RGBA file but some artifacts appears. It seems the channels with 0xFFFF values is not correctly decoded.

![hasselblad-allplanes-fail](https://cloud.githubusercontent.com/assets/7633907/11323967/2721ae7c-9123-11e5-83f2-fe4747246041.png)

**Comment by jonsneyers** [comment] 2015-11-23 22:21
https://github.com/FLIF-hub/FLIF/commit/02350fca7bc5e20d0a106360a1fd6a65eaf5b8ce fixed this, right?

**Comment by psykauze** [comment] 2015-11-23 22:43
Not at all. I think the issue is at the decoder part or image-pam.cpp part.

**Comment by psykauze** [comment] 2015-11-23 23:06
How to reproduce this error:
1) raw2rggb Hasselblad H4D-60.fff Hasselblad.rggb
2) flif Hasselblad.rggb Hasselblad.flif
3) flif -d Hasselblad.flif Hasselblad.pam < Artifacts are shown yet
4) convert Hasselblad.pam -channel RGBA -separate -swap 0,1 -swap 2,3 -swap 0,2 -combine .Hasselblad-2.pam

**Comment by jonsneyers** [comment] 2015-11-24 06:29
Smells like an overflow of an uint16_t somewhere.

**Comment by psykauze** [comment] 2015-11-24 10:12
I've tried with PNG and had also the same issue. It's seems it's not limited to PAM. I've checked image-pam.cpp and I didn't see anything weird.

I've also tried to read output files with The GIMP but same artifacts as with Imagemagick "display". (The GIMP can't decode properly 48bpp files so it's not a recommended product).

My assumption is, there is a "+1" somewhere. I will check this evening with an hex editor.

**Comment by jonsneyers** [comment] 2015-11-24 12:19
Decoding .flif to .rggb produces the exact same file as the original .rggb.

Running `dcraw` on the original .fff file produces a .ppm file with the same artifacts.

So I think this is not a flif issue...

**Comment by psykauze** [comment] 2015-11-25 11:54
OK, I will check if it's a dcraw issue. Also, my debian package of dcraw seems outdated.

I think, working directly with DNG will be better. The most complete tool for converting raw to DNG seems to be the Adobe one.

**Comment by StephanBusch** [comment] 2015-11-25 12:25
I also think that working directly with DNG would be better. Maybe this project helps:
https://github.com/jmue/dngconvert

**Comment by jonsneyers** [comment] 2015-11-27 14:04
Closing this issue, since the artifacts are either caused by dcraw or actually present in the source image.

**Closed by jonsneyers** 2015-11-27 14:04 UTC
Labels: bug, raw
