### ISSUE TITLE
Small palette interpolation is broken

### ISSUE THREAD

**Issue by orlp** [FLIF-hub/FLIF#211] opened 2016-01-27 23:02 UTC
Take this paletted PNG (32 colors, generated with pngquant): http://i.imgur.com/0tmdoSP.png

Now try running this:

```
wget http://i.imgur.com/0tmdoSP.png -O starry.png
flif -e starry.png starry.flif
flif -d starry.flif starry100.ppm
flif -d -q50 starry.flif starry50.ppm
flif -d -q49 starry.flif starry49.png
sha1sum starry100.ppm starry50.ppm
```
You'll see that 50 quality is exactly equivalent to full quality, yet 49 quality is an instant really big downgrade. Something is going wrong here.

**Comment by jonsneyers** [comment] 2016-01-28 10:43
Actually this is normal behavior, even though I understand that it is somewhat counter-intuitive.
It helps to use lots of verbosity `-vvvvvv` to see what is going on here.

The `--quality` decode parameter behaves as follows:
the image gets decoded, one channel/zoomlevel at a time, until at least X percent of the subpixels have been decoded. Only full zoomlevels are decoded, not partial ones (in this sense, it is different from simply truncating the file, which can interrupt the stream in the middle of a zoomlevel).

Usually subpixels are Y, Co, Cg (with priority to Y), so 50% of the subpixels means quite a good quality (just some chroma subsampling).
However, with palette images, the channels are condensed into one palette-indexed channel, which does indeed harm the progressive decode quality (but it does tend to give better compression).
Since there is only one channel, every subpixel corresponds to a full pixel.

Only full zoomlevels are decoded (to avoid getting images where the upper part looks better than the lower part). The final zoomlevel encodes half of the pixels in a palette (or grayscale) image. So quality 50 or higher forces the decoder to decode the full image. Qualities between 25 and 49 would decode everything except the final zoomlevel, so you get all even-numbered rows but not the odd-numbered rows (counting from zero). This is of course a big downgrade from the full-resolution image. Especially because for palette images, nearest neighbor interpolation is used instead of linear interpolation, since linear interpolation does not make sense on palette indexes.

So as a result, FLIF files with a palette are less suitable for lower-quality decoding. Of course we could change the way `-q` works by also allowing partial zoomlevel decoding (to get closer to the desired quality target), but that would result in images where the top looks better than the bottom, which is not really desirable.

One way to avoid the problem is by disabling palette, using the encode option `-P0`. In that case, the ColorBucket transform should take over, so the compressed size will typically not be that much worse than with the default (palette) encoding. The advantage of ColorBucket over Palette is that the Y Co Cg channels are still there, so the 'good' progressive decoding is not harmed and the decode quality parameter will have a more fine-grained behavior. Especially in palette images which originate from quantized full-color images, this is often a good idea.

Can I close the issue with these remarks or does anyone have a suggestion on how to improve things?
Disabling palette by default is the only "solution" I can see that would solve this particular problem, but it would increase compressed size for many images.

**Comment by orlp** [comment] 2016-01-28 11:18
Thanks for the comprehensive explanation, that makes sense.

One remark, would it make sense to interlace the zoom levels themselves in the bitstream (it's interlacing all the way down!), such that when a file gets truncated mid-zoomlevel it can use the partial data from that zoomlevel to improve the quality of the image without making one half of the image look significantly better?

Or would that simply destroy compression by reducing locality?

**Comment by jonsneyers** [comment] 2016-01-28 11:47
"Interlacing all the way down" is an interesting idea. I'm not sure if it can be done without severely complicating the prediction and context model, as well as speed (memory locality) and compression (entropy locality). Certainly an idea to consider for a future version of FLIF.

I don't expect that to significantly improve progressive decoding though, since it would mostly have the effect of making the final decode stages more fine-grained, not so much the early stages.

A bigger impact to improve progressive decoding could be obtained by doing some kind of DCT, or by postponing least significant bits of the subpixels (in particular the chroma subpixels). Though it might be hard to do that without harming overall compression.

**Comment by orlp** [comment] 2016-01-28 12:11
@jonsneyers I have one more question regarding truncation. Would it be preferable to ignore any partial zoomlevel on truncation, only showing full zoomlevels? Technically this would be worse quality (if I were to go by SSIM), but it would make the image seem a lot less glitchy.

An example of an image in which the top half clearly has better quality: http://i.imgur.com/UW443jt.png

```
wget http://i.imgur.com/0tmdoSP.png -O starry.png
flif -e -q0 starry.png starry.flif  
head -c 7000 starry.flif > starry_trunc.flif
flif -d starry_trunc.flif starry_trunc.png
```

Perhaps it's advisable to make both behaviors available (partial and full-only) through an option, and add the number of available zoomlevels to the identification (`-i`).

**Comment by jonsneyers** [comment] 2016-01-28 12:54
The identification only decodes the header, it would become much slower if it had to actually attempt to decode the image to find out if (and where) the file was truncated.

Since unexpected file ends are only detected when they occur, ignoring partial zoomlevels would mean actively undoing the partially decoded zoomlevel (i.e. replace it by an interpolation instead of the already decoded values). That would be easy to do, I could add a command line option for that. You can simulate the behavior by manually specifying the correct percentage. If you don't mind some trickery:
```
flif starry_trunc.flif starry_trunc.png -q`flif -vvvvvv starry_trunc.flif null: | grep Unexpected | cut -f 1 -d%`
```
should do the trick in your example :)

I consider truncated files to be broken files. There are various ways to deal with broken files: refuse to decode them, try to make them look as good as possible (even if that means discarding some information), or show as much as possible. I picked the last option, but those other options are of course also reasonable.

The normal way to get low-quality previews would be not by using truncation, but by using the `-q` (or `-s` or `-r`) command line option, or by using the library interface with a progressive decoding callback function (like in `viewflif`). In those cases, only full zoomlevels are shown, exactly to avoid the glitchy look of partial zoomlevels.

**Comment by jonsneyers** [comment] 2016-04-02 07:48
Changing it so that partially decoded / truncated palette images get interpolated in Y Co Cg color space with the usual bilinear interpolation, instead of doing nearest neighbor with the palette indexes. Commit will be pushed soon.

**Closed** 2016-04-02 08:13 UTC
Labels: progressive rendering
