### ISSUE TITLE
png to flif & flif to flif: different output 

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#91] opened 2015-10-15 15:00 UTC
```
./flif ./tools/2_webp_ll.png ./test1.flif
./flif -t ./test1.flif ./test2.flif
./flif -t ./test2.flif ./test3.flif
sha1sum test1.flif test2.flif test3.flif

0e0caa159252c7ccb30998b7ab7297a0b9cb057b  test1.flif
86ef4e2ade55db39bfe8eb7986bd1aedfb03503a  test2.flif
86ef4e2ade55db39bfe8eb7986bd1aedfb03503a  test3.flif
```
shouldn't test1, test2 and test3 technically all be the same file?

**Comment by jonsneyers** [comment] 2015-10-15 15:42
Yes. I wonder what strange kind of magic is happening here.
test2.flif and test3.flif are the same if you do this, and they're smaller than test1.flif (about 2kb or almost 10% !).
And yes, test2.flif still decodes to the same image, it's not a bug.

I guess the explanation is that the MANIAC trees are conditioned by the decoding step, which results in a better tree in the encoding step. This confirms my hypothesis that the MANIAC tree learning is still very naive and there is margin for improvement! Nice!

**Comment by jonsneyers** [comment] 2015-10-16 08:40
Still, I wonder where the difference comes from, the decoder should not leak to the encoder...

**Comment by psykauze** [comment] 2015-10-19 20:13
I've just tested the e7daed2 commit with the "fractal art 2" set and did some conversion.

Here the results:
1) Original PNG to interlaced FLIF: 74262584 bytes
2) interlaced FLIF to interlaced FLIF: 75188826 bytes
3) Decoded PNG (from "1") to interlaced FLIF: 75188826 bytes

1) Original PNG to non-interlaced FLIF: 63883117 bytes
2) non-interlaced FLIF to non-interlaced FLIF: 63883121 bytes
3) Decoded PNG (from "1") to non-interlaced FLIF: 63883121 bytes

I can't explain this weird results.

**Comment by psykauze** [comment] 2015-10-20 06:06
Not all the files have this issue (I only tested the size difference). I've compared the PNG files that their flif size differs with "compare -verbose -metrics mae". Results of compare is "0" everywhere (for r, g, b, a and total).

I does not try yet if the second flif is a "lossy/bogus" picture.

I does not try to convert the original files to pnm with imagemagick before.

I does not try if a PNG"crushed" file make a different flif file.

**Comment by jonsneyers** [comment] 2015-10-20 08:01
OK, I figured it out. Turns it it was related to the alpha channel: FLIF does not encode the RGB values of A=0 pixels (fully transparent pixels), and uses interpolated values instead. This in itself is not the issue, but some of the transforms (BND, ACB, PLT) did not take this into account. For some images this made a difference. Will be fixed in a few minutes.

**Closed** 2015-10-20 08:26 UTC
Labels: help wanted
